height = 'height'
tx_pool = 'tx_pool'

owner_publicKey = 'ownerpublickey'
node_publicKey = 'nodepublickey'
tx_ela_number = 'tx_ela_number'
tx_ela_amount = 'tx_ela_amount'
asset_regiset_number = 'asset_regiset_number'
tx_asset_number = 'tx_asset_number'

sponsor = 'sponsor'
view_offset = 'viewoffset'
votes = 'votes'
state = 'state'
producers = 'producers'

nickname = 'nickname'
amount = 'amount'
txid_index = 'txid_index'
txid = 'txid'
vout = 'vout'
candidates = 'candidates'

inactive = 'inactive'
illegal = 'illegal'
arbiters = 'arbiters'
next_arbiters = 'nextarbiters'
next_candidates = 'nextcandidates'
onduty_arbiter = 'ondutyarbiter'
current_turn_start_height = 'currentturnstartheight'
next_turn_start_height = 'nextturnstartheight'
